### ISSUE TITLE
Play 2.3

### ISSUE THREAD

**Issue by pbelmann** [fizzed/play-module-twitter#2]
Could you provide a version for play 2.3.x?

**Comment by jjlauer** [comment]
Ironically, I was working on Play 2.2 and Play 2.3 support yesterday.  Just finished up support for both versions.  See the README.md for a compatibility matrix for which version you'll want to pick.  Also, please note that I migrated the package from the com.mfizz group/organization to com.fizzed group/organization.  So you'll need to pull a new dependency AND update some of your import statements, play.plugins etc to simply use com.fizzed in place of com.mfizz.
